// Imports
// ========================================================
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import RootProvider from "./provider";

// Config
// ========================================================
const inter = Inter({ subsets: ["latin"] });

// Metadata
// ========================================================
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Main Layout
// ========================================================
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RootProvider>{children}</RootProvider>
      </body>
    </html>
  );
}
